### PR TITLE
Documentation created automatically

### PR DESCRIPTION
**Pull request by abelsiqueira**
This uses some pieces from the man page and the function arguments to create a simple documentation for the core interface.

### CODE REVIEW

**Comment by dpo** [comment]
If we're going to keep generating this documentation automatically, I'm wondering if we should store it in a separate file. I believe there's a way to attach a docstring to a function defined elsewhere.

I'm not insisting, but it looks like most of the file is taken up by the docstrings now, which makes it harder to navigate. What do you think?

**Comment by abelsiqueira** [comment]
I tried to do that when using the man pages using something from the documentation but it didn't work. I will have time tomorrow and will test it again.

**Comment by abelsiqueira** [comment]
I could only use [Docile's external file](http://docilejl.readthedocs.org/en/latest/syntax/) when also using Lexicon, and I could only make it work on 0.4.
The documentation isn't clear enough on this point, maybe because of the migration of `@doc` to 0.4.

**Comment by dpo** [comment]
What I had in mind is something like this (from the link you gave):
```JULIA
"""
Method ``f(::Any)``.
"""
f(x) = x

"""
Function ``f`` after definition.
"""
f
```

The definition of `f` could appear in one file, and its documentation in another, that is `include`d.

**Comment by abelsiqueira** [comment]
That worked, but 0.3 has the limitation of not showing in the REPL. Should I add a conditional `import Lexicon` as mentioned [here](https://github.com/MichaelHatherly/Docile.jl/issues/79) or wait for 0.4?

**Comment by dpo** [comment]
Is there a way to require it only for 0.3?

**Comment by abelsiqueira** [comment]
From what I (didn't) found, it looks like there isn't. [Someone asked a similar question](https://groups.google.com/forum/#!searchin/julia-users/REQUIRE/julia-users/A2mgX0xyd8s/Ucl1CtwzqRYJ) on julia-users and the sole answer was negative. I also looked at other packages using Docile and no one did it.

**Comment by dpo** [comment]
I propose that we not require `Docile`. We don't need `Docile` because we're using plain docstrings. Users need `Lexicon` if they want enhanced documentation. I've started removing `Docile` from several other of my packages too. What do you think?

**Comment by abelsiqueira** [comment]
Agreed

**Comment by abelsiqueira** [comment]
I will destroy some commits in this

**Comment by abelsiqueira** [comment]
Commits squashed.

**Comment by dpo** [comment]
Thanks! Will it also be possible to document the specialized interface? If the documentation is stored in a different file, I'm not sure how that works?!

**Comment by abelsiqueira** [comment]
I believe it's possible too, I'll just create another file with the documentation for the specialized, but it may take a little more time because of all the variations in the interface.
I will make a different PR for that.

**Comment by abelsiqueira** [comment]
I noticed, running the script again in other computer, that the terminal size was interfering with the manual pages size, regardless of being called inside the script. So I fixed by setting the man width size to a large value. This also removes hyphenation and justification.

**Comment by abelsiqueira** [comment]
With the last commit, both documentations are created.
I'd rather rebase this after the fix #41, and squash the commits, if you think the output is good enough.

**Comment by abelsiqueira** [comment]
I was gonna use `@doc (@doc foo) foo!`, but that doesn't work on 0.3

**Comment by dpo** [comment]
Let's use plain docstrings everywhere. They work on 0.3 with Docile, and natively on 0.4.

**Comment by abelsiqueira** [comment]
That's what I did. It's on file `src/documentation.jl`.

**Comment by dpo** [comment]
Well actually, maybe I'm wrong about that. I can't get any documentation to show in 0.3. Can you?

**Comment by dpo** [comment]
Sorry that's not true. I get the docstrings from the Julia interface, but that's all. So defining the docstring elsewhere doesn't work in 0.3 at all, is that right?

**Comment by abelsiqueira** [comment]
You're right, the documentation is not working with 0.3. In fact I needed Docile and Lexicon and to use `@doc """ ... """ ->`. 
This also works with 0.4 without Docile and Lexicon.

To fix we need to return to `if VERSION < ...` and add Docile to `REQUIRE`.
Should we do it, or wait until 0.4 is stable?

**Comment by dpo** [comment]
Let's wait until 0.4 I think. I like the way you've set things up.

**Comment by dpo** [comment]
Any chance that you could rebase?

**Comment by abelsiqueira** [comment]
No problem. Rebased

**Comment by dpo** [comment]
Thanks! Sorry I was away for a while.

**Pull request merged**
